spring:
  h2:
    console:
      enabled: true
      path: /h2_console
  datasource:
    url: jdbc:h2:~/h2database/moviedb;AUTO_SERVER=TRUE
    username: root
    password: root
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

tmdb:
  api:
    base:
      url: https://api.themoviedb.org/3
  apikey: f27e0ddb97639a603e486473a151892d
  language: en-US